services:    
  db:
    container_name: db_postgres_container
    image: postgres:latest
    environment:
      POSTGRES_db: "dbshop"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "1234"
    volumes:
      - db_data:/var/lib/postgressql/data
    ports:
      - "5432:5432"
volumes:
  db_data: