version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__InternetShopDbContext=Host=userdb;Port=5432;Database=dbshop;Username=bogda;Password=1234
      - Jwt__Key=your_secure_key_here
    depends_on:
      - userdb
      - catalogdb
      - redis

  userdb:
    image: postgres:latest
    environment:
      POSTGRES_USER: bogda
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: dbshop
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  catalogdb:
    image: mongo:6.0
    ports:
      - "27017:27017"  # Проброс порта на localhost
    environment:
      MONGO_INITDB_DATABASE: dbcatalog
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  mongo_data:
  redis_data: